import React, {useEffect} from "react";
import Head from "next/head";
import {AppBadge, AppButton, AppDivider, AppPagination, AppTable} from "../../../components/Main";
import styles from "../../../styles/reports.module.scss";

import FilterIcon from "../../../assets/images/icons/filled/filter.svg";
import {useAppDispatch, useAppSelector} from "../../../core/hooks";
import {useRouter} from "next/router";
import Moment from "react-moment";
import {getAllVisitForeignSpecialistsReportsThunk} from "../../../core/store/report/visitForeignSpecialists/visitForeignSpecialists.thunks";
import {setAllVisitForeignSpecialistsReportsAction} from "../../../core/store/report/visitForeignSpecialists/visitForeignSpecialists.slices";

const VisitForeignSpecialistsListPage = () => {
	const dispatch = useAppDispatch();
	const visitForeignSpecialistsReport = useAppSelector(
		({visitForeignSpecialistsReport}) => visitForeignSpecialistsReport,
	);

	const router = useRouter();

	useEffect(() => {
		const promises = [dispatch(getAllVisitForeignSpecialistsReportsThunk())];

		return () => {
			promises.forEach((p) => p.abort());
			setAllVisitForeignSpecialistsReportsAction({list: [], count: 0});
		};
	}, []);

	const onOpenReport = (reportId: number) => () => {
		void router.push(`/reports/visit-foreign-specialists/${reportId}`);
	};

	const renderTableBodyRow = () => {
		return visitForeignSpecialistsReport.list.map((report) => (
			<tr onClick={onOpenReport(report.id)} key={report.id}>
				<td>{report.id}</td>
				<td>{report.id}</td>
				<td>
					<Moment format="DD.MM.YYYY">{report.createdAt}</Moment>
				</td>
				<td>{report.organization.title.ru}</td>
				<td>{report.note ?? "-"}</td>
				<td>
					<AppBadge statusId={report.status.id} className="mx-auto" variant="warning">
						{report.status.title.ru}
					</AppBadge>
				</td>
			</tr>
		));
	};

	return (
		<>
			<Head>
				<title>Визит иностранных специалистов (ОЦ)</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<h1 className="h1 text-center">Визит иностранных специалистов (ОЦ)</h1>

			<AppDivider className="my-1.25" />

			<div className={styles.filters}>
				<div className={styles.filterLabel}>
					<AppButton variant="primary-outline" size="lg" withIcon>
						<FilterIcon width="24px" height="24px" className="main-btn-text-color" />
						<span>Фильтр</span>
					</AppButton>
				</div>

				<div className={styles.filterLabel}>
					<span className="text-main-bold">Статус:</span>
					<div className="d-flex gap-0.125">
						<AppButton className="active" variant="primary-outline" size="lg">
							Все
						</AppButton>
						<AppButton variant="primary-outline" size="lg">
							Отправлен
						</AppButton>
						<AppButton variant="primary-outline" size="lg">
							Принят
						</AppButton>
						<AppButton variant="primary-outline" size="lg">
							Отказан
						</AppButton>
					</div>
				</div>

				<AppButton
					useAs="link"
					href="/reports/visit-foreign-specialists/create"
					className="ms-auto"
					variant="main"
					size="lg"
				>
					Создать
				</AppButton>
			</div>

			<AppTable linked>
				<AppTable.THead>
					<tr>
						<th>ID</th>
						<th>Номер</th>
						<th>Дата</th>
						<th>Организация</th>
						<th>Комментарии</th>
						<th>Статус</th>
					</tr>
				</AppTable.THead>
				<AppTable.TBody>{renderTableBodyRow()}</AppTable.TBody>
			</AppTable>

			<div className="mt-auto">
				<AppDivider className="my-1.25" />
				<AppPagination />
			</div>
		</>
	);
};

export default VisitForeignSpecialistsListPage;
