import Head from "next/head";
import React, {ChangeEvent, useState} from "react";
import cn from "classnames";
import {useForm} from "react-hook-form";
import {useRouter} from "next/router";
import {AppButton, AppCard, AppDivider, AppInput} from "../../../components/Main";
import styles from "../../../styles/reports.module.scss";
import TrashIcon from "../../../assets/images/icons/filled/trash.svg";
import ChevronIcon from "../../../assets/images/icons/filled/arrows/chevron-left.svg";
import SuccessIcon from "../../../assets/images/icons/filled/checked.svg";
import {useAppDispatch} from "../../../core/hooks";
import {IReportAppealsCreateParams} from "../../../core/models";
import {createAppealsReportThunk} from "../../../core/store/report/appeals/appeals-report.thunks";

const fieldOptions = {
	required: true,
	valueAsNumber: true,
};

const AppealsReportCreatePage = () => {
	const router = useRouter();

	const dispatch = useAppDispatch();

	const {register, handleSubmit, getValues} = useForm<IReportAppealsCreateParams>();

	const [files, setFiles] = useState<File[]>([]);
	const [errText, setErrText] = useState("");

	const onSubmit = async (fields: IReportAppealsCreateParams) => {
		const numberValues: number[] = Object.values(getValues());

		if (numberValues.length) {
			const sum = numberValues.reduce((accumulator, currentValue) => {
				if (!isNaN(currentValue)) {
					return accumulator + currentValue;
				} else {
					return accumulator;
				}
			}, 0);

			if (sum === files.length) {
				setErrText("");
				const formData = new FormData();
				files.forEach((f) => formData.append("files", f));

				const action = await dispatch(createAppealsReportThunk({payload: fields, formData}));
				const id = action.payload as number;

				if (id) {
					void router.push(`/reports/appeals/${id}`);
				}
			} else {
				setErrText(`Количество людей должно совпадать с количеством привязанных документов.`);
			}
		}
	};

	const onFileChange = (e: ChangeEvent<HTMLInputElement>) => {
		if (e.target.files) {
			for (const key in e.target.files) {
				const file = e.target.files[key];

				if (file instanceof File) {
					if (!files.some((f) => f.name === file.name)) {
						setFiles((prev) => [...prev, file]);
					}
				}
			}
		}
	};

	const onFileRemove = (fileName: string) => () => {
		const index = files.findIndex((f) => f.name === fileName);
		setFiles((prev) => prev.filter((f, i) => i !== index));
	};

	const renderFiles = () => {
		return files.map((file) => (
			<div className="flex-center gap-0.5" key={file.name}>
				<label className={styles.cardBodyLabel}>
					<AppInput className="text-center" type="file" disabled readOnly placeholder={file.name} />
				</label>

				<AppButton onClick={onFileRemove(file.name)} variant="danger" size="square">
					<TrashIcon width="24px" height="24px" />
				</AppButton>
			</div>
		));
	};

	return (
		<>
			<Head>
				<title>Обращение физических и юридических лиц</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<h1 className="h1 text-center">Обращение физических и юридических лиц</h1>

			<AppDivider className="my-1.25" />

			<div className={styles.filters}>
				<label className={styles.filterLabel}>
					<span className="text-main-bold">Дата</span>

					<AppInput type="date" />
				</label>

				<label className={styles.filterLabel}>
					<span className="text-main-bold">Номер:</span>
					<AppButton variant="main" size="square">
						80
					</AppButton>
				</label>
			</div>
			<div className={cn(styles.cardDesk, styles.cardDeskGrid4)}>
				<div className={styles.cardWrapper}>
					<AppCard className="h-100">
						<AppCard.Header>Подтверждающий документ</AppCard.Header>
						<AppCard.Body className={cn(styles.cardBody, styles.fileCardBody)}>
							<label className={styles.cardBodyLabel}>
								<AppInput
									onChange={onFileChange}
									className="text-center"
									type="file"
									placeholder="Прикрепить файл"
									multiple
								/>
							</label>

							<AppDivider className="my-0.75" />

							{renderFiles()}
							{errText}
						</AppCard.Body>
					</AppCard>
				</div>

				<div className={cn(styles.cardWrapper, styles.columnFillFrom2)}>
					<AppCard>
						<AppCard.Header>Обращения</AppCard.Header>
						<AppCard.Body className={cn(styles.cardBody, styles.grid2)}>
							<label className={styles.cardBodyLabel}>
								<span className="text-main-bold">Жалобы:</span>
								<AppInput
									className="text-center"
									type="number"
									placeholder="0"
									{...register("complaints", fieldOptions)}
								/>
							</label>

							<label className={styles.cardBodyLabel}>
								<span className="text-main-bold">Задачи по другим темам:</span>
								<AppInput
									className="text-center"
									type="number"
									placeholder="0"
									{...register("questions", fieldOptions)}
								/>
							</label>
						</AppCard.Body>
					</AppCard>
				</div>
			</div>

			<div className="flex-justify-between mt-auto pt-2.5">
				<AppButton useAs="link" href="/reports/appeals" size="lg" variant="dark" withIcon>
					<ChevronIcon width="24px" height="24px" />
					Назад
				</AppButton>
				<AppButton onClick={handleSubmit(onSubmit)} size="lg" variant="success" withIcon>
					<SuccessIcon width="24px" height="24px" />
					<span>Отправить отчёт</span>
				</AppButton>
			</div>
		</>
	);
};

export default AppealsReportCreatePage;
