import React, {useEffect} from "react";
import Head from "next/head";
import {AppButton, AppCard, AppDivider, AppTable} from "../../../components/Main";
import ChevronIcon from "../../../assets/images/icons/filled/arrows/chevron-left.svg";
import {useRouter} from "next/router";
import {useAppDispatch, useAppSelector} from "../../../core/hooks";
import {
	changeStatusOfFinancialExpensesReportThunk,
	getFinancialExpensesReportByIdThunk,
} from "../../../core/store/report/financialExpenses/financial-expenses-report.thunks";
import {setFinancialExpenseReportByIdAction} from "../../../core/store/report/financialExpenses/financial-expenses-report.slices";
import {eReportStatusType} from "../../../core/models";

const CenterFinancialExpensesListInfoPage = () => {
	const router = useRouter();
	const reportId = router.query["reportId"] as string;

	const dispatch = useAppDispatch();
	const report = useAppSelector(({financialExpensesReport}) => financialExpensesReport.current);

	useEffect(() => {
		if (reportId) {
			const id = +reportId;

			if (!isNaN(id)) {
				const promises = [dispatch(getFinancialExpensesReportByIdThunk(id))];

				return () => {
					promises.forEach((p) => p.abort());
					dispatch(setFinancialExpenseReportByIdAction(null));
				};
			}
		}
	}, [reportId]);

	const onClick = (statusTypeId: eReportStatusType) => () => {
		dispatch(changeStatusOfFinancialExpensesReportThunk({id: +reportId, statusId: statusTypeId}));
	};

	if (!report) return null;

	return (
		<>
			<Head>
				<title>
					Республика ихтисослаштирилган онкология ва тиббий радиология илмий-амалий тиббиёт маркази tibbiyot markazining
					17.11.2022
				</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<h1 className="h1 text-center">
				Республика ихтисослаштирилган онкология ва тиббий радиология илмий-амалий тиббиёт маркази tibbiyot markazining
				17.11.2022
			</h1>

			<AppDivider className="my-1.25" />

			<div className="flex-col gap-2.5">
				<AppCard shadow="table">
					<AppTable wrapperClassName="p-0">
						<AppTable.THead extended>
							<tr>
								<th>Kомандировки (бюджет, внебюджет)</th>
								<th>Зарплата и премии (внебюджет)</th>
								<th>Капитальный и частичный ремонт</th>
								<th>Учеба и повышение квалификации</th>
								<th>На лекарства и расходные материалы</th>
							</tr>
						</AppTable.THead>
						<AppTable.TBody>
							<tr>
								<td>2</td>
								<td>2</td>
								<td>84</td>
								<td>84</td>
								<td>65203100</td>
							</tr>
						</AppTable.TBody>
					</AppTable>
				</AppCard>

				<AppCard shadow="table">
					<AppTable wrapperClassName="p-0">
						<AppTable.THead extended>
							<tr>
								<th>Медицинский инвентарь</th>
								<th>Спонсортсво</th>
								<th>Наука (гранд, инноватция и тд)</th>
								<th>Расходы по 2 группе</th>
								<th>Прочие расходы</th>
							</tr>
						</AppTable.THead>
						<AppTable.TBody>
							<tr>
								<td>44</td>
								<td>10</td>
								<td>34</td>
								<td>6</td>
								<td>2</td>
							</tr>
						</AppTable.TBody>
					</AppTable>
				</AppCard>
			</div>
			{/*TODO: add padding-top to avoid adhesion in small heights of screen*/}
			<div className="flex-justify-between mt-auto pe-2.5">
				<AppButton useAs="link" href="/reports/financial-expenses" size="lg" variant="dark" withIcon>
					<ChevronIcon width="24px" height="24px" />
					Назад
				</AppButton>
				<div className="d-flex gap-0.5">
					<AppButton onClick={onClick(eReportStatusType.Rejected)} size="lg" variant="danger">
						Отказать
					</AppButton>
					<AppButton onClick={onClick(eReportStatusType.Approved)} size="lg" variant="success">
						Принять
					</AppButton>
				</div>
			</div>
		</>
	);
};

export default CenterFinancialExpensesListInfoPage;
