import React, {useEffect} from "react";
import Head from "next/head";
import {AppButton, AppDivider, AppTable} from "../../../components/Main";
import ChevronIcon from "../../../assets/images/icons/filled/arrows/chevron-left.svg";
import {useRouter} from "next/router";
import {useAppDispatch, useAppSelector} from "../../../core/hooks";
import {ReportPageUpdate} from "../../../components/Layout";
import {getScientificWorksReportByIdThunk} from "../../../core/store/report/scientificWorks/scientific-works-report.thunks";
import {setScientificWorksReportByIdAction} from "../../../core/store/report/scientificWorks/scientific-works-report.slices";
import {eTable} from "../../../core/models";

const ScientificWorksReportInfoPage = () => {
	const router = useRouter();
	const reportId = router.query["reportId"] as string;

	const dispatch = useAppDispatch();
	const report = useAppSelector(({scientificWorksReport}) => scientificWorksReport.current);

	useEffect(() => {
		if (reportId) {
			const id = +reportId;

			if (!isNaN(id)) {
				const promises = [dispatch(getScientificWorksReportByIdThunk(id))];

				return () => {
					promises.forEach((p) => p.abort());
					dispatch(setScientificWorksReportByIdAction(null));
				};
			}
		}
	}, [reportId]);

	if (!report) return null;

	return (
		<div className="pe-0 flex-col h-100">
			<Head>
				<title>{report.organization.title.ru}</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<h1 className="h1 text-center">{report.organization.title.ru}</h1>

			<AppDivider className="my-1.25" />

			<AppTable>
				<AppTable.THead extended>
					<tr>
						<th colSpan={6}>Количество статей</th>
						<th colSpan={3}>Количество лекций</th>
						<th colSpan={4}>Другие</th>
					</tr>
					<tr>
						<th>Местные</th>
						<th>Зарубежные</th>
						<th>СНГ</th>
						<th>Scopus</th>
						<th>WoS</th>
						<th>Другие</th>
						<th>Местные</th>
						<th>Зарубежные</th>
						<th>СНГ</th>
						<th>Монографии</th>
						<th>Патенты</th>
						<th>Методические пособия</th>
						<th>Методические рекомендации</th>
					</tr>
				</AppTable.THead>
				<AppTable.TBody>
					<tr>
						<td>{report.localArticles}</td>
						<td>{report.foreignArticles}</td>
						<td>{report.cisArticles}</td>
						<td>{report.scopusArticles}</td>
						<td>{report.wosArticles}</td>
						<td>{report.otherArticles}</td>
						<td>{report.localLectures}</td>
						<td>{report.foreignLectures}</td>
						<td>{report.cisLectures}</td>
						<td>{report.monographs}</td>
						<td>{report.patents}</td>
						<td>{report.benefits}</td>
						<td>{report.recommendations}</td>
					</tr>
				</AppTable.TBody>
			</AppTable>

			<div className="flex-justify-between mt-auto pe-2.5">
				<AppButton useAs="link" href="/reports/scientific-works" size="lg" variant="dark" withIcon>
					<ChevronIcon width="24px" height="24px" />
					Назад
				</AppButton>

				<ReportPageUpdate
					reportOrganizationId={report.organization.id}
					reportCreatorId={report.user?.id}
					reportStatusId={report.status.id}
					paternalId={report.organization.paternalId}
					reportId={+reportId}
					table={eTable.ScientificWorksReport}
				/>
			</div>
		</div>
	);
};

export default ScientificWorksReportInfoPage;
