import React, {useEffect, useState} from "react";
import Head from "next/head";
import {AppDivider, AppPagination, AppSetOfReportsFilter, AppTable} from "../../../components/Main";
import {useAppDispatch} from "../../../core/hooks";
import {getSetOfReportsThunks} from "../../../core/store/setOfReports/setOfReports.thunks";
import {ISetOfReportsInsurance, ISetOfReportsParams} from "../../../core/models";
import moment from "moment/moment";
import Moment from "react-moment";

const InsuranceSetOfReportsPage = () => {
	const dispatch = useAppDispatch();

	const [results, setResults] = useState<{count: number; data: ISetOfReportsInsurance[]}>();
	const [filters, setFilters] = useState<ISetOfReportsParams>({
		take: 20,
		skip: 0,
		start: moment().subtract(1, "months").startOf("month").format("yyyy-MM-DD"),
		end: moment().endOf("month").format("yyyy-MM-DD"),
		organizations: [],
	});

	useEffect(() => {
		const promise = dispatch(
			getSetOfReportsThunks({
				url: "insurance",
				params: filters,
			}),
		);

		promise.then((action) =>
			setResults((prev) => {
				const result = action.payload as typeof results;
				if (result) {
					return {count: result.count, data: result.data};
				}
				return prev;
			}),
		);

		return () => {
			promise.abort();
		};
	}, [filters]);

	const onFilterSubmit = (params: ISetOfReportsParams) => {
		setFilters((prev) => ({...prev, ...params}));
	};

	const onPagination = (pagination: {take: number; skip: number}) => {
		setFilters((prev) => ({...prev, ...pagination}));
	};

	const renderRow = () => {
		return results?.data.map((r, i) => (
			<tr key={`${r.createdAt.toString()}-${i}`}>
				<td>
					<Moment format="DD.MM.YYYY">{r.createdAt}</Moment>
				</td>
				<td>{r._sum.acts}</td>
				<td>{r._sum.amountOfActs}</td>
				<td>{r._sum.approvedActs}</td>
				<td>{r._sum.amountOfApprovedActs}</td>
				<td>{r._sum.rejectedActs}</td>
				<td>{r._sum.amountOfRejectedActs}</td>
				<td>{r._sum.amountOfSentApprovedInvoices}</td>
				<td>{r._sum.fundedAmount}</td>
				<td>{r._sum.patients}</td>
				<td>{r._sum.annualAmount}</td>
				<td>{r._sum.residualAmount}</td>
			</tr>
		));
	};

	return (
		<div className="pe-0 flex-col h-100">
			<Head>
				<title>
					Информация о размере финансирования из государственного фонда медицинского страхования (название центра)
				</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<h1 className="h1 text-center">
				Информация о размере финансирования из государственного фонда медицинского страхования (название центра)
			</h1>

			<AppDivider className="my-1.25" />

			<div className="pe-2.5">
				<AppSetOfReportsFilter exportUrl="insurance" onFilterSubmit={onFilterSubmit} />
			</div>

			{(results?.data?.length || -1) > 0 ? (
				<AppTable wrapperClassName="mb-1.5">
					<AppTable.THead extended>
						<tr>
							{/* TODO: URGENT add date to all report id pages */}
							<th>Дата</th>
							<th colSpan={2}>Акты, поданные на рассмотренеие в ГФМС</th>
							<th colSpan={2}>Рассмотренные и одобренные акты ГФМС</th>
							<th colSpan={2}>Рассмотренные и неодобренные акты ГФМС</th>
							<th>Расмотренные, одобренные акты и отправленные счет-фактуры</th>
							<th>Финансирования со стороны ГФМС</th>
							<th>Количество пациентов получивших лечение на основе льготного напрваления</th>
							<th>Итоговый годовой контракт</th>
							<th>Остаток относительно суммы контракта</th>
						</tr>
						<tr>
							<th>Количество</th>
							<th>Сумма</th>
							<th>Количество</th>
							<th>Сумма</th>
							<th>Количество</th>
							<th>Сумма</th>
							<th>Сумма</th>
							<th>Сумма</th>
							<th>Сумма</th>
							<th>Сумма</th>
							<th>Сумма</th>
							<th>Сумма</th>
							{/* TODO: URGENT SHOW ALSO GENERATED FIELDS	*/}
						</tr>
					</AppTable.THead>
					<AppTable.TBody>{renderRow()}</AppTable.TBody>
				</AppTable>
			) : (
				"Список отчётов пуст."
			)}
			<div className="mt-auto pe-2.5">
				<AppDivider className="my-1.25" />
				<AppPagination totalCount={results?.count} cb={onPagination} />
			</div>
		</div>
	);
};

export default InsuranceSetOfReportsPage;
