import React, {useEffect} from "react";
import Head from "next/head";
import {AppButton, AppDivider, AppPagination, AppTable} from "../../components/Main";
import {useAppDispatch, useAppSelector} from "../../core/hooks";
import {useRouter} from "next/router";
import {getAllOrganizationsThunk} from "../../core/store/organization/organization.thunks";
import {setAllOrganizationsAction} from "../../core/store/organization/organization.slices";

const OrganizationsListPage = () => {
	const router = useRouter();

	const organization = useAppSelector(({organization}) => organization);
	const dispatch = useAppDispatch();

	useEffect(() => {
		const promise = dispatch(getAllOrganizationsThunk());

		return () => {
			promise.abort();
			dispatch(setAllOrganizationsAction({list: [], count: 0}));
		};
	}, []);

	const onPagination = (params: {skip: number; take: number}) => {
		dispatch(getAllOrganizationsThunk(params));
	};

	const onOpenOrganization = (id: number) => () => {
		void router.push(`/organizations/${id}`);
	};

	const renderTableBodyRow = () => {
		return organization.list.map((o) => (
			<tr onClick={onOpenOrganization(o.id)} key={o.id}>
				<td>{o.id}</td>
				<td>{o.title.ru}</td>
			</tr>
		));
	};

	return (
		<>
			<Head>
				<title>Организации</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<h1 className="h1 text-center">Организации</h1>

			<AppDivider className="my-1.25" />

			<AppButton useAs="link" href="/organizations/create" className="ms-auto  mb-1.25" variant="main" size="lg">
				Создать
			</AppButton>

			{organization.list.length > 0 ? (
				<AppTable linked wrapperClassName="p-0">
					<AppTable.THead>
						<tr>
							<th>ID</th>
							<th>Организация</th>
						</tr>
					</AppTable.THead>
					<AppTable.TBody>{renderTableBodyRow()}</AppTable.TBody>
				</AppTable>
			) : (
				"Список организаций пуст."
			)}

			<div className="mt-auto">
				<AppDivider className="my-1.25" />
				<AppPagination cb={onPagination} totalCount={organization.count} />
			</div>
		</>
	);
};

export default OrganizationsListPage;
