import React, {useEffect} from "react";
import Head from "next/head";
import {AppBadge, AppDivider, AppPagination, AppTable} from "../../../components/Main";

import {useAppDispatch, useAppSelector} from "../../../core/hooks";
import {useRouter} from "next/router";
import {getAllTelemedicineReportsThunk} from "../../../core/store/report/telemedicine/telemedicine.thunks";
import {setAllTelemedicineReportsAction} from "../../../core/store/report/telemedicine/telemedicine.slices";
import Moment from "react-moment";
import {eTable} from "../../../core/models";
import {ReportListPageWrapper} from "../../../components/Layout";

const TelemedicineReportListPage = () => {
	const dispatch = useAppDispatch();
	const telemedicineReport = useAppSelector(({telemedicineReport}) => telemedicineReport);

	const router = useRouter();

	useEffect(() => {
		const promises = [dispatch(getAllTelemedicineReportsThunk())];

		return () => {
			promises.forEach((p) => p.abort());
			dispatch(setAllTelemedicineReportsAction({list: [], count: 0}));
		};
	}, []);

	const onOpenReport = (reportId: number) => () => {
		void router.push(`/reports/telemedicine/${reportId}`);
	};

	const renderTableBodyRow = () => {
		return telemedicineReport.list.map((report) => (
			<tr onClick={onOpenReport(report.id)} key={report.id}>
				<td>{report.id}</td>
				<td>{report.id}</td>
				<td>
					<Moment format="DD.MM.YYYY">{report.createdAt}</Moment>
				</td>
				<td>{report.organization.title.ru}</td>
				<td>{report.note ?? "-"}</td>
				<td>
					<AppBadge statusId={report.status.id} className="mx-auto">
						{report.status.title.ru}
					</AppBadge>
				</td>
			</tr>
		));
	};
	return (
		<>
			<Head>
				<title>Телемедицина (ОЦ)</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<h1 className="h1 text-center">Телемедицина (ОЦ)</h1>

			<AppDivider className="my-1.25" />

			<ReportListPageWrapper table={eTable.TelemedicineReport}>
				{telemedicineReport.list.length > 0 ? (
					<AppTable linked wrapperClassName="p-0">
						<AppTable.THead>
							<tr>
								<th>Область</th>
								<th>Кол-во консультаций</th>
								<th>Кол-во консилиумов:</th>
								<th>Кол-во показательных операций</th>
								<th>Кол-во семинаров, (мacтep.к)</th>
								<th>Кол-во симпозиумов, (к)</th>
							</tr>
						</AppTable.THead>
						<AppTable.TBody>{renderTableBodyRow()}</AppTable.TBody>
					</AppTable>
				) : (
					"Список отчётов пуст."
				)}

				<div className="mt-auto">
					<AppDivider className="my-1.25" />
					<AppPagination />
				</div>
			</ReportListPageWrapper>
		</>
	);
};

export default TelemedicineReportListPage;
