import React, {useEffect} from "react";
import Head from "next/head";
import {AppBadge, AppButton, AppDivider, AppPagination, AppTable} from "../../../components/Main";
import styles from "../../../styles/reports.module.scss";

import FilterIcon from "../../../assets/images/icons/filled/filter.svg";
import {useAppDispatch, useAppSelector} from "../../../core/hooks";
import {getAllDailyReportsThunk} from "../../../core/store/report/daily/daily-report.thunks";
import {setAllDailyReportsAction} from "../../../core/store/report/daily/daily-report.slices";
import Moment from "react-moment";
import {useRouter} from "next/router";

const DailyListPage = () => {
	const dispatch = useAppDispatch();
	const dailyReport = useAppSelector(({dailyReport}) => dailyReport);

	const router = useRouter();

	useEffect(() => {
		dispatch(getAllDailyReportsThunk());

		return () => {
			setAllDailyReportsAction({list: [], count: 0});
		};
	}, []);

	const onOpenReport = (reportId: number) => () => {
		void router.push(`daily/${reportId}`);
	};

	const renderTableBodyRow = () => {
		return dailyReport.list.map((report) => (
			<React.Fragment key={report.id}>
				<AppTable.TBody>
					<tr onClick={onOpenReport(report.id)}>
						<td>{report.id}</td>
						<td>{report.id}</td>
						<td>
							<Moment format="DD.MM.YYYY">{report.createdAt}</Moment>
						</td>
						<td>Болалар гематологияси онкологияси ва клиник иминология маркази (309211410)</td>
						<td>{report.notes ?? "-"}</td>
						<td>
							<AppBadge statusId={report.status.id} className="mx-auto">
								{report.status.title.ru}
							</AppBadge>
						</td>
					</tr>
				</AppTable.TBody>
			</React.Fragment>
		));
	};

	return (
		<>
			<Head>
				<title>Ежедневный отчёт</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<h1 className="h1 text-center">Ежедневный отчёт</h1>

			<AppDivider className="my-1.25" />

			<div className={styles.filters}>
				<div className={styles.filterLabel}>
					<AppButton variant="primary-outline" size="lg" withIcon>
						<FilterIcon width="24px" height="24px" className="main-btn-text-color" />
						<span>Фильтр</span>
					</AppButton>
				</div>

				<div className={styles.filterLabel}>
					<span className="text-main-bold">Статус:</span>
					<div className="d-flex gap-0.125">
						<AppButton className="active" variant="primary-outline" size="lg">
							Все
						</AppButton>
						<AppButton variant="primary-outline" size="lg">
							Отправлен
						</AppButton>
						<AppButton variant="primary-outline" size="lg">
							Принят
						</AppButton>
						<AppButton variant="primary-outline" size="lg">
							Отказан
						</AppButton>
					</div>
				</div>

				<AppButton useAs="link" href="/reports/daily/create" className="ms-auto" variant="main" size="lg">
					Создать
				</AppButton>
			</div>

			<AppTable className="linked-table" wrapperClassName="p-0">
				<AppTable.THead>
					<tr>
						<th>ID</th>
						<th>Номер</th>
						<th>Дата</th>
						<th>Организация</th>
						<th>Комментарии</th>
						<th>Статус</th>
					</tr>
				</AppTable.THead>
				{renderTableBodyRow()}
			</AppTable>

			<div className="mt-auto">
				<AppDivider className="my-1.25" />
				<AppPagination />
			</div>
		</>
	);
};

export default DailyListPage;
