import React from "react";
import Head from "next/head";
import cn from "classnames";
import {AppButton, AppCard, AppDivider, AppInput} from "../../components/Main";
import styles from "../../styles/reports.module.scss";
import PlusIcon from "../../assets/images/icons/filled/plus.svg";
import TrashIcon from "../../assets/images/icons/filled/trash.svg";
import ChevronIcon from "../../assets/images/icons/filled/arrows/chevron-left.svg";
import SuccessIcon from "../../assets/images/icons/filled/checked.svg";

const SciencePage = () => {
	return (
		<>
			<Head>
				<title>Наука (ОЦ)</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<h1 className="h1 text-center">Наука (ОЦ)</h1>

			<AppDivider className="my-1.25" />

			<div className={styles.filters}>
				<label className={styles.filterLabel}>
					<span className="text-main-bold">Дата</span>
					<AppInput type="date" />
				</label>

				<label className={styles.filterLabel}>
					<span className="text-main-bold">Номер:</span>
					<AppButton variant="main" size="square">
						80
					</AppButton>
				</label>
			</div>

			<AppCard>
				<AppCard.Header>Номер заявки</AppCard.Header>
				<AppCard.Body className="grid-col-4 gap-1">
					<label className={styles.cardBodyLabel}>
						<span className="text-main-bold">Статьи и тезисы:</span>
						<div className="w-100">
							<AppInput className="text-center" type="number" placeholder="0" />
						</div>
					</label>

					<label className={styles.cardBodyLabel}>
						<span className="text-main-bold">Защита научных диссертаций:</span>
						<div className="w-100">
							<AppInput className="text-center" type="number" placeholder="0" />
						</div>
					</label>

					<label className={styles.cardBodyLabel}>
						<span className="text-main-bold">Патенты:</span>
						<div className="w-100">
							<AppInput className="text-center" type="number" placeholder="0" />
						</div>
					</label>

					<label className={styles.cardBodyLabel}>
						<span className="text-main-bold">Методические руководства:</span>
						<div className="w-100">
							<AppInput className="text-center" type="number" placeholder="0" />
						</div>
					</label>
				</AppCard.Body>
			</AppCard>

			<AppDivider className="my-2 mx-auto" style={{width: "16.25rem"}} />

			<div className={cn(styles.cardDesk, styles.cardDeskGrid2, styles.bgWhite)}>
				<div className={styles.cardWrapper}>
					<AppCard className="h-100">
						<AppCard.Header>Местные</AppCard.Header>
						<AppCard.Body className="flex-col gap-2.5">
							<div className={cn("gap-1", styles.percentGrid3)}>
								<label className={styles.cardBodyLabel}>
									<span className="text-main-bold">Срок:</span>
									<div className="w-100">
										<AppInput type="date" />
									</div>
								</label>

								<label className={cn("flex-fill", styles.cardBodyLabel)}>
									<span className="text-main-bold">Наименование:</span>
									<div className="w-100">
										<AppInput className="text-center" type="text" placeholder="-" />
									</div>
								</label>

								<div className={styles.cardBodyLabel}>
									<span className="text-main-bold">Действие:</span>
									<AppButton variant="dark" size="square" withIcon>
										<PlusIcon width="24px" height="24px" />
									</AppButton>
								</div>
							</div>

							<div className={cn("gap-1", styles.percentGrid3)}>
								<AppInput className="w-100" type="date" />

								<AppInput className="text-center w-100" type="text" placeholder="-" />

								<div className="flex-center">
									<AppButton variant="danger" size="square" withIcon>
										<TrashIcon width="24px" height="24px" />
									</AppButton>
								</div>
							</div>
						</AppCard.Body>
					</AppCard>
				</div>

				<div className={styles.cardWrapper}>
					<AppCard className="h-100">
						<AppCard.Header>Местные</AppCard.Header>
						<AppCard.Body className="flex-col gap-2.5">
							<div className={cn("gap-1", styles.percentGrid3)}>
								<label className={styles.cardBodyLabel}>
									<span className="text-main-bold">Срок:</span>
									<div className="w-100">
										<AppInput type="date" />
									</div>
								</label>

								<label className={cn("flex-fill", styles.cardBodyLabel)}>
									<span className="text-main-bold">Наименование:</span>
									<div className="w-100">
										<AppInput className="text-center" type="text" placeholder="-" />
									</div>
								</label>

								<div className={styles.cardBodyLabel}>
									<span className="text-main-bold">Действие:</span>
									<AppButton variant="dark" size="square" withIcon>
										<PlusIcon width="24px" height="24px" />
									</AppButton>
								</div>
							</div>

							<div className={cn("gap-1", styles.percentGrid3)}>
								<AppInput className="w-100" type="date" />

								<AppInput className="text-center w-100" type="text" placeholder="-" />

								<div className="flex-center">
									<AppButton variant="danger" size="square" withIcon>
										<TrashIcon width="24px" height="24px" />
									</AppButton>
								</div>
							</div>
						</AppCard.Body>
					</AppCard>
				</div>
			</div>

			{/* TODO: make a component to avoid duplicates */}
			<div className="flex-justify-between mt-auto pt-2.5">
				<AppButton useAs="link" href="/" size="lg" variant="dark" withIcon>
					<ChevronIcon width="24px" height="24px" />
					Назад
				</AppButton>
				<AppButton size="lg" variant="success" withIcon>
					<SuccessIcon width="24px" height="24px" />
					<span>Отправить отчёт</span>
				</AppButton>
			</div>
		</>
	);
};

export default SciencePage;
