import React from "react";
import Head from "next/head";
import {AppButton, AppCard, AppDivider, AppInput} from "../../components/Main";
import styles from "../../styles/reports.module.scss";
import cn from "classnames";
import TrashIcon from "../../assets/images/icons/filled/trash.svg";
import ChevronIcon from "../../assets/images/icons/filled/arrows/chevron-left.svg";
import SuccessIcon from "../../assets/images/icons/filled/checked.svg";

const AppealsPage = () => {
	return (
		<>
			<Head>
				<title>Ежедневный отчёт</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<h1 className="h1 text-center">Ежедневный отчёт</h1>

			<AppDivider className="my-1.25" />

			<div className={styles.filters}>
				<label className={styles.filterLabel}>
					<span className="text-main-bold">Дата</span>
					<AppInput type="date" />
				</label>

				<label className={styles.filterLabel}>
					<span className="text-main-bold">Номер:</span>
					<AppButton variant="main" size="square">
						80
					</AppButton>
				</label>
			</div>

			<div className={cn(styles.cardDesk, styles.cardDeskGrid4)}>
				<div className={styles.cardWrapper}>
					<AppCard className="h-100">
						<AppCard.Header>Подтверждающий документ</AppCard.Header>
						<AppCard.Body className={cn(styles.cardBody, styles.fileCardBody)}>
							<label className={styles.cardBodyLabel}>
								<AppInput className="text-center" type="file" placeholder="Прикрепить файл" />
							</label>

							<AppDivider className="my-0.75" />

							<div className="flex-center gap-0.5">
								<label className={styles.cardBodyLabel}>
									<AppInput className="text-center" type="file" placeholder="Название документа" />
								</label>

								<AppButton variant="danger" size="square">
									<TrashIcon width="24px" height="24px" />
								</AppButton>
							</div>
						</AppCard.Body>
					</AppCard>
				</div>

				<div className={cn(styles.cardWrapper, styles.columnFillFrom2)}>
					<AppCard>
						<AppCard.Header>Обращения</AppCard.Header>
						<AppCard.Body className={cn(styles.cardBody, styles.grid2)}>
							<label className={styles.cardBodyLabel}>
								<span className="text-main-bold">Жалобы:</span>
								<AppInput className="text-center" type="number" placeholder="0" />
							</label>

							<label className={styles.cardBodyLabel}>
								<span className="text-main-bold">Задачи по другим темам:</span>
								<AppInput className="text-center" type="number" placeholder="0" />
							</label>
						</AppCard.Body>
					</AppCard>
				</div>
			</div>

			<div className="flex-justify-between mt-auto pt-2.5">
				<AppButton useAs="link" href="/" size="lg" variant="dark" withIcon>
					<ChevronIcon width="24px" height="24px" />
					Назад
				</AppButton>
				<AppButton size="lg" variant="success" withIcon>
					<SuccessIcon width="24px" height="24px" />
					<span>Отправить отчёт</span>
				</AppButton>
			</div>
		</>
	);
};

export default AppealsPage;
