import React from "react";
import Head from "next/head";
import {AppButton, AppCard, AppDivider, AppInput, AppTable} from "../../components/Main";
import ChevronIcon from "../../assets/images/icons/filled/arrows/chevron-left.svg";
import styles from "../../styles/reports.module.scss";
import TrashIcon from "../../assets/images/icons/filled/trash.svg";

const AppealsListInfoPage = () => {
	return (
		<>
			<Head>
				<title>
					Республиканский специализированный научно-практический медицинский центр кардиологии tibbiyot markazining
					17.11.2022
				</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<h1 className="h1 text-center">
				Республиканский специализированный научно-практический медицинский центр кардиологии tibbiyot markazining
				17.11.2022
			</h1>

			<AppDivider className="my-1.25" />

			<div className="flex-col gap-2.5">
				<AppCard shadow="table">
					<AppTable wrapperClassName="p-0">
						<AppTable.THead extended>
							<tr>
								<th>Kомандировки (бюджет, внебюджет)</th>
								<th>Зарплата и премии (внебюджет)</th>
							</tr>
						</AppTable.THead>
						<AppTable.TBody>
							<tr>
								<td>2</td>
								<td>2</td>
							</tr>
						</AppTable.TBody>
					</AppTable>
				</AppCard>

				<div>
					<AppCard className="w-max" shadow="table">
						<AppTable className="w-max" wrapperClassName="p-0">
							<AppTable.THead extended>
								<tr>
									<th>Kомандировки (бюджет, внебюджет)</th>
									<th>Зарплата и премии (внебюджет)</th>
								</tr>
							</AppTable.THead>
							<AppTable.TBody>
								<tr>
									<td>2</td>
									<td>2</td>
								</tr>
							</AppTable.TBody>
						</AppTable>
					</AppCard>
				</div>

				<div className="flex-center gap-0.5 w-max">
					<label className={styles.cardBodyLabel}>
						<AppInput className="text-center" type="file" placeholder="Название документа" />
					</label>

					<AppButton variant="danger" size="square">
						<TrashIcon width="24px" height="24px" />
					</AppButton>
				</div>
			</div>
			{/*TODO: add padding-top to avoid adhesion in small heights of screen*/}
			<div className="flex-justify-between mt-auto pe-2.5">
				<AppButton useAs="link" href="/" size="lg" variant="dark" withIcon>
					<ChevronIcon width="24px" height="24px" />
					Назад
				</AppButton>
				<div className="d-flex gap-0.5">
					<AppButton size="lg" variant="danger">
						Отказать
					</AppButton>
					<AppButton size="lg" variant="success">
						Принять
					</AppButton>
				</div>
			</div>
		</>
	);
};

export default AppealsListInfoPage;
