import React from "react";
import Head from "next/head";
import {AppButton, AppCard, AppDivider, AppTable} from "../../components/Main";
import ChevronIcon from "../../assets/images/icons/filled/arrows/chevron-left.svg";

const CenterFinancialExpensesListInfoPage = () => {
	return (
		<>
			<Head>
				<title>
					Республика ихтисослаштирилган онкология ва тиббий радиология илмий-амалий тиббиёт маркази tibbiyot markazining
					17.11.2022
				</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<h1 className="h1 text-center">
				Республика ихтисослаштирилган онкология ва тиббий радиология илмий-амалий тиббиёт маркази tibbiyot markazining
				17.11.2022
			</h1>

			<AppDivider className="my-1.25" />

			<div className="flex-col gap-2.5">
				<AppCard shadow="table">
					<AppTable wrapperClassName="p-0">
						<AppTable.THead extended>
							<tr>
								<th>Kомандировки (бюджет, внебюджет)</th>
								<th>Зарплата и премии (внебюджет)</th>
								<th>Капитальный и частичный ремонт</th>
								<th>Учеба и повышение квалификации</th>
								<th>На лекарства и расходные материалы</th>
							</tr>
						</AppTable.THead>
						<AppTable.TBody>
							<tr>
								<td>2</td>
								<td>2</td>
								<td>84</td>
								<td>84</td>
								<td>65203100</td>
							</tr>
						</AppTable.TBody>
					</AppTable>
				</AppCard>

				<AppCard shadow="table">
					<AppTable wrapperClassName="p-0">
						<AppTable.THead extended>
							<tr>
								<th>Медицинский инвентарь</th>
								<th>Спонсортсво</th>
								<th>Наука (гранд, инноватция и тд)</th>
								<th>Расходы по 2 группе</th>
								<th>Прочие расходы</th>
							</tr>
						</AppTable.THead>
						<AppTable.TBody>
							<tr>
								<td>44</td>
								<td>10</td>
								<td>34</td>
								<td>6</td>
								<td>2</td>
							</tr>
						</AppTable.TBody>
					</AppTable>
				</AppCard>
			</div>
			{/*TODO: add padding-top to avoid adhesion in small heights of screen*/}
			<div className="flex-justify-between mt-auto pe-2.5">
				<AppButton useAs="link" href="/" size="lg" variant="dark" withIcon>
					<ChevronIcon width="24px" height="24px" />
					Назад
				</AppButton>
				<div className="d-flex gap-0.5">
					<AppButton size="lg" variant="danger">
						Отказать
					</AppButton>
					<AppButton size="lg" variant="success">
						Принять
					</AppButton>
				</div>
			</div>
		</>
	);
};

export default CenterFinancialExpensesListInfoPage;
