import React from "react";
import Head from "next/head";
import {AppButton, AppCard, AppDivider, AppInput} from "../../components/Main";
import styles from "../../styles/reports.module.scss";
import cn from "classnames";
import ChevronIcon from "../../assets/images/icons/filled/arrows/chevron-left.svg";
import SuccessIcon from "../../assets/images/icons/filled/checked.svg";

const CenterFinancialExpensesPage = () => {
	return (
		<>
			<Head>
				<title>Финансовые расходы центра (ОЦ)</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<h1 className="h1 text-center">Финансовые расходы центра (ОЦ)</h1>

			<AppDivider className="my-1.25" />

			<div className={styles.filters}>
				<label className={styles.filterLabel}>
					<span className="text-main-bold">Дата</span>

					<AppInput type="date" />
				</label>

				<label className={styles.filterLabel}>
					<span className="text-main-bold">Номер:</span>
					<AppButton variant="main" size="square">
						80
					</AppButton>
				</label>
			</div>

			<div className={cn(styles.cardDesk, styles.cardDeskGrid2)}>
				<div className={styles.cardWrapper}>
					<AppCard className="h-100">
						<AppCard.Body className={cn("gap-0.5", styles.cardRows)}>
							<label className={cn("flex-justify-between gap-1", styles.cardRow)}>
								<span className={cn("rounded text-main-bold flex-fill", styles.cardRowLabel)}>
									Kомандировки (бюджет, внебюджет)
								</span>
								<AppInput className="text-center" type="number" placeholder="0" />
							</label>

							<label className={cn("flex-justify-between gap-1", styles.cardRow)}>
								<span className={cn("rounded text-main-bold flex-fill", styles.cardRowLabel)}>
									Зарплата и премии (внебюджет)
								</span>
								<AppInput className="text-center" type="number" placeholder="0" />
							</label>

							<label className={cn("flex-justify-between gap-1", styles.cardRow)}>
								<span className={cn("rounded text-main-bold flex-fill", styles.cardRowLabel)}>
									Капитальный и частичный ремонт
								</span>
								<AppInput className="text-center" type="number" placeholder="0" />
							</label>

							<label className={cn("flex-justify-between gap-1", styles.cardRow)}>
								<span className={cn("rounded text-main-bold flex-fill", styles.cardRowLabel)}>Спонсортсво</span>
								<AppInput className="text-center" type="number" placeholder="0" />
							</label>

							<label className={cn("flex-justify-between gap-1", styles.cardRow)}>
								<span className={cn("rounded text-main-bold flex-fill", styles.cardRowLabel)}>
									Наука (гранд, инноватция и тд)
								</span>
								<AppInput className="text-center" type="number" placeholder="0" />
							</label>
						</AppCard.Body>
					</AppCard>
				</div>

				<div className={styles.cardWrapper}>
					<AppCard className="h-100">
						<AppCard.Body className={cn("gap-0.5", styles.cardRows)}>
							<label className={cn("flex-justify-between gap-1", styles.cardRow)}>
								<span className={cn("rounded text-main-bold flex-fill", styles.cardRowLabel)}>
									Учеба и повышение квалификации
								</span>
								<AppInput className="text-center" type="number" placeholder="0" />
							</label>

							<label className={cn("flex-justify-between gap-1", styles.cardRow)}>
								<span className={cn("rounded text-main-bold flex-fill", styles.cardRowLabel)}>
									На лекарства и расходные материалы
								</span>
								<AppInput className="text-center" type="number" placeholder="0" />
							</label>

							<label className={cn("flex-justify-between gap-1", styles.cardRow)}>
								<span className={cn("rounded text-main-bold flex-fill", styles.cardRowLabel)}>
									Медицинский инвентарь
								</span>
								<AppInput className="text-center" type="number" placeholder="0" />
							</label>

							<label className={cn("flex-justify-between gap-1", styles.cardRow)}>
								<span className={cn("rounded text-main-bold flex-fill", styles.cardRowLabel)}>Расходы по 2 группе</span>
								<AppInput className="text-center" type="number" placeholder="0" />
							</label>

							<label className={cn("flex-justify-between gap-1", styles.cardRow)}>
								<span className={cn("rounded text-main-bold flex-fill", styles.cardRowLabel)}>Прочие расходы</span>
								<AppInput className="text-center" type="number" placeholder="0" />
							</label>
						</AppCard.Body>
					</AppCard>
				</div>
			</div>

			<div className="flex-justify-between mt-auto">
				<AppButton useAs="link" href="/" size="lg" variant="dark" withIcon>
					<ChevronIcon width="24px" height="24px" />
					Назад
				</AppButton>
				<AppButton size="lg" variant="success" withIcon>
					<SuccessIcon width="24px" height="24px" />
					<span>Сохранить</span>
				</AppButton>
			</div>
		</>
	);
};

export default CenterFinancialExpensesPage;
