import React from "react";
import Head from "next/head";
import {AppButton, AppCard, AppDivider, AppTable} from "../../components/Main";
import ChevronIcon from "../../assets/images/icons/filled/arrows/chevron-left.svg";

const RegionsWorkDoneListInfoPage = () => {
	return (
		<>
			<Head>
				<title>
					Республика ихтисослаштирилган онкология ва тиббий радиология илмий-амалий тиббиёт маркази tibbiyot markazining
					17.11.2022
				</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<h1 className="h1 text-center">
				Республика ихтисослаштирилган онкология ва тиббий радиология илмий-амалий тиббиёт маркази tibbiyot markazining
				17.11.2022
			</h1>

			<AppDivider className="my-1.25" />

			<div className="flex-col gap-2.5">
				<AppCard shadow="table">
					<AppTable wrapperClassName="p-0">
						<AppTable.THead extended>
							<tr>
								<th>Конференция, симпозиум ва х.к</th>
								<th>Учеба/повышение квалификации до 10 дней</th>
								<th>Учеба/повышение квалификации от 10 до 30 дней</th>
								<th>Учеба/повышение квалификации более 30 дней</th>
							</tr>
						</AppTable.THead>
						<AppTable.TBody>
							<tr>
								<td>2</td>
								<td>2</td>
								<td>84</td>
								<td>5</td>
							</tr>
						</AppTable.TBody>
					</AppTable>
				</AppCard>

				<AppCard shadow="table">
					<AppTable wrapperClassName="p-0">
						<AppTable.THead extended>
							<tr>
								<th>Кол-во выявленных пациетов</th>
								<th>В том числе, кол-во пациентов для амбулаторного лечения</th>
								<th>В том числе, кол-во пациентов для стационарного лечения</th>
								<th>Кол-во мастер-классов проведенных в регионе</th>
								<th>Кол-во семинаров проведенных в регионе</th>
							</tr>
						</AppTable.THead>
						<AppTable.TBody>
							<tr>
								<td>44</td>
								<td>10</td>
								<td>34</td>
								<td>6</td>
								<td>2</td>
							</tr>
						</AppTable.TBody>
					</AppTable>
				</AppCard>

				<AppCard shadow="table">
					<AppTable wrapperClassName="p-0">
						<AppTable.THead extended>
							<tr>
								<th>Кол-во операций проведенных в регионе</th>
								<th>В том числе, кол-во высокотехнологичных операций</th>
								<th>Кол-во новых внедрений по диагностике в регионе</th>
								<th>Кол-во новых внедрений по диагностике в регионе</th>
								<th>Кол-во специалистов получившие квалификацию на местах</th>
							</tr>
						</AppTable.THead>
						<AppTable.TBody>
							<tr>
								<td>2</td>
								<td>1</td>
								<td>1</td>
								<td>0</td>
								<td>0</td>
							</tr>
						</AppTable.TBody>
					</AppTable>
				</AppCard>
			</div>
			{/*TODO: add padding-top to avoid adhesion in small heights of screen*/}
			<div className="flex-justify-between mt-auto pe-2.5">
				<AppButton useAs="link" href="/" size="lg" variant="dark" withIcon>
					<ChevronIcon width="24px" height="24px" />
					Назад
				</AppButton>
				<div className="d-flex gap-0.5">
					<AppButton size="lg" variant="danger">
						Отказать
					</AppButton>
					<AppButton size="lg" variant="success">
						Принять
					</AppButton>
				</div>
			</div>
		</>
	);
};

export default RegionsWorkDoneListInfoPage;
