import React from "react";
import Head from "next/head";
import {AppButton, AppCard, AppDivider, AppInput} from "../../components/Main";
import styles from "../../styles/reports.module.scss";
import cn from "classnames";
import ChevronIcon from "../../assets/images/icons/filled/arrows/chevron-left.svg";
import SuccessIcon from "../../assets/images/icons/filled/checked.svg";

const RegionsWorkDonePage = () => {
	return (
		<>
			<Head>
				<title>Проделанная работа в регионах (ОЦ)</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<h1 className="h1 text-center">Проделанная работа в регионах (ОЦ)</h1>

			<AppDivider className="my-1.25" />

			<div className={styles.filters}>
				<label className={styles.filterLabel}>
					<span className="text-main-bold">Дата</span>

					<AppInput type="date" />
				</label>

				<label className={styles.filterLabel}>
					<span className="text-main-bold">Номер:</span>
					<AppButton variant="main" size="square">
						80
					</AppButton>
				</label>
			</div>

			<div className={cn(styles.cardDesk, styles.cardDeskGrid2)}>
				<div className={styles.cardWrapper}>
					<AppCard className="h-100">
						<AppCard.Body className={cn("gap-0.5", styles.cardRows)}>
							<label className={cn("flex-justify-between gap-1", styles.cardRow)}>
								<span className={cn("rounded text-main-bold flex-fill", styles.cardRowLabel)}>
									Кол-во выездов в регионы
								</span>
								<AppInput className="text-center" type="number" placeholder="0" />
							</label>

							<label className={cn("flex-justify-between gap-1", styles.cardRow)}>
								<span className={cn("rounded text-main-bold flex-fill", styles.cardRowLabel)}>
									Кол-во специалистов посетивших регионы
								</span>
								<AppInput className="text-center" type="number" placeholder="0" />
							</label>

							<label className={cn("flex-justify-between gap-1", styles.cardRow)}>
								<span className={cn("rounded text-main-bold flex-fill", styles.cardRowLabel)}>
									Кол-во мастер-классов проведенных в регионе
								</span>
								<AppInput className="text-center" type="number" placeholder="0" />
							</label>

							<label className={cn("flex-justify-between gap-1", styles.cardRow)}>
								<span className={cn("rounded text-main-bold flex-fill", styles.cardRowLabel)}>
									Кол-во семинаров проведенных в регионе
								</span>
								<AppInput className="text-center" type="number" placeholder="0" />
							</label>

							<label className={cn("flex-justify-between gap-1", styles.cardRow)}>
								<span className={cn("rounded text-main-bold flex-fill", styles.cardRowLabel)}>
									Кол-во специалситов получившие квалификацию на местах
								</span>
								<AppInput className="text-center" type="number" placeholder="0" />
							</label>
						</AppCard.Body>
					</AppCard>
				</div>

				<div className={styles.cardWrapper}>
					<AppCard className="h-100">
						<AppCard.Body className={cn("gap-0.5", styles.cardRows)}>
							<label className={cn("flex-justify-between gap-1", styles.cardRow)}>
								<span className={cn("rounded text-main-bold flex-fill", styles.cardRowLabel)}>
									Кол-во населения прошедших медосмотр
								</span>
								<AppInput className="text-center" type="number" placeholder="0" />
							</label>

							<label className={cn("flex-justify-between gap-1", styles.cardRow)}>
								<span className={cn("rounded text-main-bold flex-fill", styles.cardRowLabel)}>
									В том числе, дети до 18 лет
								</span>
								<AppInput className="text-center" type="number" placeholder="0" />
							</label>

							<label className={cn("flex-justify-between gap-1", styles.cardRow)}>
								<span className={cn("rounded text-main-bold flex-fill", styles.cardRowLabel)}>
									Кол-во выявленных пациетов
								</span>
								<AppInput className="text-center" type="number" placeholder="0" />
							</label>

							<label className={cn("flex-justify-between gap-1", styles.cardRow)}>
								<span className={cn("rounded text-main-bold flex-fill", styles.cardRowLabel)}>
									В том числе, кол-во пациентов для амбулаторного лечения
								</span>
								<AppInput className="text-center" type="number" placeholder="0" />
							</label>

							<label className={cn("flex-justify-between gap-1", styles.cardRow)}>
								<span className={cn("rounded text-main-bold flex-fill", styles.cardRowLabel)}>
									В том числе, кол-во пациентов для стационарного лечения
								</span>
								<AppInput className="text-center" type="number" placeholder="0" />
							</label>
						</AppCard.Body>
					</AppCard>
				</div>
			</div>

			<div className={cn(styles.cardDesk, styles.cardDeskGrid2)}>
				<div className={styles.cardWrapper}>
					<AppCard className="h-100">
						<AppCard.Body className={cn("gap-0.5", styles.cardRows)}>
							<label className={cn("flex-justify-between gap-1", styles.cardRow)}>
								<span className={cn("rounded text-main-bold flex-fill", styles.cardRowLabel)}>
									Кол-во операций проведенных в регионе
								</span>
								<AppInput className="text-center" type="number" placeholder="0" />
							</label>

							<label className={cn("flex-justify-between gap-1", styles.cardRow)}>
								<span className={cn("rounded text-main-bold flex-fill", styles.cardRowLabel)}>
									В том числе, кол-во высокотехнологичных операций
								</span>
								<AppInput className="text-center" type="number" placeholder="0" />
							</label>
						</AppCard.Body>
					</AppCard>
				</div>

				<div className={styles.cardWrapper}>
					<AppCard className="h-100">
						<AppCard.Body className={cn("gap-0.5", styles.cardRows)}>
							<label className={cn("flex-justify-between gap-1", styles.cardRow)}>
								<span className={cn("rounded text-main-bold flex-fill", styles.cardRowLabel)}>
									Кол-во новых внедрений по диагностике в регионе
								</span>
								<AppInput className="text-center" type="number" placeholder="0" />
							</label>

							<label className={cn("flex-justify-between gap-1", styles.cardRow)}>
								<span className={cn("rounded text-main-bold flex-fill", styles.cardRowLabel)}>
									Кол-во новых внедрений по лечению в регионе
								</span>
								<AppInput className="text-center" type="number" placeholder="0" />
							</label>
						</AppCard.Body>
					</AppCard>
				</div>
			</div>

			<div className="flex-justify-between mt-auto">
				<AppButton useAs="link" href="/" size="lg" variant="dark" withIcon>
					<ChevronIcon width="24px" height="24px" />
					Назад
				</AppButton>
				<AppButton size="lg" variant="success" withIcon>
					<SuccessIcon width="24px" height="24px" />
					<span>Отправить отчёт</span>
				</AppButton>
			</div>
		</>
	);
};

export default RegionsWorkDonePage;
