import React from "react";
import Head from "next/head";
import {AppButton, AppCard, AppDivider, AppInput} from "../../components/Main";
import styles from "../../styles/reports.module.scss";
import cn from "classnames";
import TrashIcon from "../../assets/images/icons/filled/trash.svg";
import ChevronIcon from "../../assets/images/icons/filled/arrows/chevron-left.svg";
import SuccessIcon from "../../assets/images/icons/filled/checked.svg";
import PlusIcon from "../../assets/images/icons/filled/plus.svg";
import {ReactSelect} from "../../components/External";

const VisitForeignSpecialistsPage = () => {
	return (
		<>
			<Head>
				<title>Телемедицина (ОЦ)</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<h1 className="h1 text-center">Телемедицина (ОЦ)</h1>

			<AppDivider className="my-1.25" />

			<div className={styles.filters}>
				<label className={styles.filterLabel}>
					<span className="text-main-bold">Дата</span>
					<AppInput type="date" />
				</label>

				<label className={styles.filterLabel}>
					<span className="text-main-bold">Номер:</span>
					<AppButton variant="main" size="square">
						80
					</AppButton>
				</label>
			</div>

			<AppCard>
				<AppCard.Header>Данные о визите</AppCard.Header>
				<AppCard.Body className="flex-col gap-2.5">
					<div>
						<div className={cn("gap-1 mb-0.5", styles.labelDeskGrid2)}>
							<div className={cn("gap-1", styles.labelDeskGrid5)}>
								<label className={styles.cardBodyLabel}>
									<span className="text-main-bold">Учреждение с кем была проведена телемедицина:</span>
								</label>
								<label className={styles.cardBodyLabel}>
									<span className="text-main-bold">Количество консультаций:</span>
								</label>
								<label className={styles.cardBodyLabel}>
									<span className="text-main-bold">Количество консилиумов:</span>
								</label>
								<label className={styles.cardBodyLabel}>
									<span className="text-main-bold">Количество показательных операций:</span>
								</label>
								<label className={styles.cardBodyLabel}>
									<span className="text-main-bold">Количество семинаров, мастер классов и т.п.:</span>
								</label>
							</div>

							<div className={styles.cardBodyLabel}>
								<span className="text-main-bold">Действие:</span>
							</div>
						</div>

						<div className={cn("gap-1", styles.labelDeskGrid2)}>
							<div className={cn("gap-1", styles.labelDeskGrid5)}>
								<label className={styles.cardBodyLabel}>
									<div className="w-100">
										<ReactSelect
											options={countryOptions}
											styles={{
												indicatorSeparator: () => ({display: "none"}),
											}}
											placeholder="Выберите учреждение"
										/>
									</div>
								</label>
								<label className={styles.cardBodyLabel}>
									<div className="w-100">
										<AppInput className="text-center" type="text" placeholder="-" />
									</div>
								</label>
								<label className={styles.cardBodyLabel}>
									<div className="w-100">
										<AppInput className="text-center" type="text" placeholder="-" />
									</div>
								</label>
								<label className={styles.cardBodyLabel}>
									<div className="w-100">
										<AppInput className="text-center" type="text" placeholder="-" />
									</div>
								</label>
								<label className={styles.cardBodyLabel}>
									<div className="w-100">
										<AppInput className="text-center" type="text" placeholder="-" />
									</div>
								</label>
							</div>

							<div className={styles.cardBodyLabel}>
								<AppButton variant="dark" size="square" withIcon>
									<PlusIcon width="24px" height="24px" />
								</AppButton>
							</div>
						</div>
					</div>
					<div className={cn("gap-1", styles.labelDeskGrid2)}>
						<div className={cn("gap-1", styles.labelDeskGrid5)}>
							<label className={styles.cardBodyLabel}>
								<div className="w-100">
									<ReactSelect options={countryOptions} placeholder="Выберите страну из..." />
								</div>
							</label>
							<label className={styles.cardBodyLabel}>
								<div className="w-100">
									<AppInput className="text-center" type="text" placeholder="-" />
								</div>
							</label>
							<label className={styles.cardBodyLabel}>
								<div className="w-100">
									<AppInput className="text-center" type="text" placeholder="-" />
								</div>
							</label>
							<label className={styles.cardBodyLabel}>
								<div className="w-100">
									<AppInput className="text-center" type="text" placeholder="-" />
								</div>
							</label>
							<label className={styles.cardBodyLabel}>
								<div className="w-100">
									<AppInput type="date" />
								</div>
							</label>
						</div>

						<div className={styles.cardBodyLabel}>
							<AppButton variant="danger" size="square" withIcon>
								<TrashIcon width="24px" height="24px" />
							</AppButton>
						</div>
					</div>
				</AppCard.Body>
			</AppCard>

			<div className="flex-justify-between mt-auto">
				<AppButton useAs="link" href="/" size="lg" variant="dark" withIcon>
					<ChevronIcon width="24px" height="24px" />
					Назад
				</AppButton>
				<AppButton size="lg" variant="success" withIcon>
					<SuccessIcon width="24px" height="24px" />
					<span>Сохранить</span>
				</AppButton>
			</div>
		</>
	);
};

export default VisitForeignSpecialistsPage;

const countryOptions = [
	{value: "andijan", label: "Андижон филиали"},
	{value: "tashkent", label: "Тошкент филиали"},
	{value: "fergana", label: "Фаргона филиали"},
];
