import React from "react";
import Head from "next/head";
import Image from "next/image";
import cn from "classnames";
import LogoImage from "../../assets/images/logo/dm-logo.png";
import styles from "../../styles/auth.module.scss";
import {AppButton, AppDropdown, LinksCardDesk, ThemeButton} from "../../components/Main";
import NotificationImage from "../../assets/images/icons/filled/notification.svg";
import UserSettingsIcon from "../../assets/images/icons/filled/users/user-settings.svg";
import Link from "next/link";

const AuthMainPage = () => {
	const onLanguageChange = (lang: {title: string; value: string | number}) => {
		console.log(lang);
	};

	return (
		<div className={cn("flex-center", styles.authPage, styles.authPageWithNav)}>
			<Head>
				<title>Главная</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<div className={cn("d-flex gap-2.625 pe-2.5 pt-1.25", styles.authPageHeader)}>
				<AppDropdown
					className={styles.headerEngLangSelect}
					textAlign="center"
					position="right"
					changeCb={onLanguageChange}
					list={languages}
				>
					<AppButton size="lg" variant="main">
						Русский
					</AppButton>
				</AppDropdown>

				<ThemeButton />
			</div>

			<div className={cn("flex-col flex-center gap-3.125", styles.authPageContent)}>
				<Image src={LogoImage} alt="" />

				<div className="flex-center gap-0.75">
					<AppButton
						className={styles.loginBtnSize}
						size="xl"
						useAs="link"
						href="/auth/signup"
						variant="primary-outline"
					>
						Регистрация
					</AppButton>
					<AppButton
						className={styles.loginBtnSize}
						size="xl"
						useAs="link"
						href="/auth/login"
						variant="primary-outline"
					>
						Войти
					</AppButton>
				</div>

				<LinksCardDesk className="text-center" list={list} />

				<nav className={cn("flex-justify-between w-100 text-main-regular rounded", styles.footerNav)}>
					<ul className="d-flex">
						<li>
							<Link href="#" className="py-0.5 px-1">
								О проекте
							</Link>
						</li>
						<li>
							<Link href="#" className="py-0.5 px-1">
								Предложения и жалобы
							</Link>
						</li>
					</ul>

					<ul className="d-flex">
						<li>
							<Link href="#" className="py-0.5 px-1">
								Реклама
							</Link>
						</li>
						<li>
							<Link href="#" className="py-0.5 px-1">
								FB
							</Link>
						</li>
						<li>
							<Link href="#" className="py-0.5 px-1">
								Instagram
							</Link>
						</li>
						<li>
							<Link href="#" className="py-0.5 px-1">
								AppStore
							</Link>
						</li>
						<li>
							<Link href="#" className="py-0.5 px-1">
								Google Play
							</Link>
						</li>
					</ul>
				</nav>
			</div>
		</div>
	);
};

export default AuthMainPage;

// TODO: move to separate file to prevent duplicates
const list = [
	{
		title: "SMAT",
		subtitle: "(электронная отчётная система)",
		url: "/reports/daily",
	},
	{
		title: "MIP",
		subtitle: "(медицинский информационный портал)",
		url: "#",
	},
	{
		title: "E-DO",
		subtitle: "(электронный документооборот)",
		url: "#",
	},
	{
		title: "E-HOSPITAL",
		subtitle: "(электронная документация клиники или электронная история болезни)",
		url: "#",
	},
	{
		title: "E-RECIPE",
		subtitle: "(электронный рецепт)",
		url: "#",
	},
	{
		title: "MED-AFISHA",
		subtitle: "(афиша всех медицинских мероприятий)",
		url: "#",
	},
	{
		title: "Мой доктор",
		subtitle: "(коммуникационная площадка пациента с врачом)",
		url: "#",
	},
	{
		title: "Мой пациент",
		subtitle: "(коммуникационная площадка врача с пациентом)",
		url: "#",
	},
];

const languages = [
	{title: "O’zbek", value: "uz"},
	{title: "English", value: "en"},
];
