import React, {useEffect} from "react";
import Head from "next/head";
import {AppButton, AppDivider, AppPagination, AppTable} from "../../components/Main";
import {useAppDispatch, useAppSelector} from "../../core/hooks";
import {getAllUsersThunk} from "../../core/store/user/user.thunks";
import {setAllUsersAction} from "../../core/store/user/user.slices";
import {useRouter} from "next/router";

const UsersListPage = () => {
	const router = useRouter();

	const user = useAppSelector(({user}) => user);
	const dispatch = useAppDispatch();

	useEffect(() => {
		const promise = dispatch(getAllUsersThunk());

		return () => {
			promise.abort();
			dispatch(setAllUsersAction({list: [], count: 0}));
		};
	}, []);

	const onPagination = (params: {skip: number; take: number}) => {
		dispatch(getAllUsersThunk(params));
	};

	const onOpenUser = (id: number) => () => {
		void router.push(`/users/${id}`);
	};

	const renderTableBodyRow = () => {
		return user.list.map((u) => (
			<tr onClick={onOpenUser(u.id)} key={u.id}>
				<td>{u.id}</td>
				<td>{u.organization.title.ru}</td>
				<td>{u.displayName.ru}</td>
			</tr>
		));
	};

	return (
		<>
			<Head>
				<title>Пользователи</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<h1 className="h1 text-center">Пользователи</h1>

			<AppDivider className="my-1.25" />

			<AppButton useAs="link" href="/users/create" className="ms-auto  mb-1.25" variant="main" size="lg">
				Создать
			</AppButton>

			{user.list.length > 0 ? (
				<AppTable linked wrapperClassName="p-0">
					<AppTable.THead>
						<tr>
							<th>ID</th>
							<th>Организация</th>
							<th>Имя</th>
						</tr>
					</AppTable.THead>
					<AppTable.TBody>{renderTableBodyRow()}</AppTable.TBody>
				</AppTable>
			) : (
				"Список пользователей пуст."
			)}

			<div className="mt-auto">
				<AppDivider className="my-1.25" />
				<AppPagination cb={onPagination} totalCount={user.count} />
			</div>
		</>
	);
};

export default UsersListPage;
