import Head from "next/head";
import {LinksCardDesk} from "../components/Main";

const HomePage = () => {
	return (
		<>
			<Head>
				<title>Главная</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<h1 className="h1 text-center mb-4.25">Главное меню</h1>
			<LinksCardDesk className="text-center" list={list} />
		</>
	);
};

export default HomePage;

const list = [
	{
		title: "SMAT",
		subtitle: "(электронная отчётная система)",
		url: "/reports/daily",
	},
	{
		title: "MIP",
		subtitle: "(медицинский информационный портал)",
		url: "#",
	},
	{
		title: "E-DO",
		subtitle: "(электронный документооборот)",
		url: "#",
	},
	{
		title: "E-HOSPITAL",
		subtitle: "(электронная документация клиники или электронная история болезни)",
		url: "#",
	},
	{
		title: "E-RECIPE",
		subtitle: "(электронный рецепт)",
		url: "#",
	},
	{
		title: "MED-AFISHA",
		subtitle: "(афиша всех медицинских мероприятий)",
		url: "#",
	},
	{
		title: "Мой доктор",
		subtitle: "(коммуникационная площадка пациента с врачом)",
		url: "#",
	},
	{
		title: "Мой пациент",
		subtitle: "(коммуникационная площадка врача с пациентом)",
		url: "#",
	},
];
