import React, {useEffect, useState} from "react";
import Head from "next/head";
import {AppBadge, AppDivider, AppPagination, AppTable} from "../../../components/Main";
import {useAppDispatch, useAppSelector} from "../../../core/hooks";
import {getAllDepartureReportsThunk} from "../../../core/store/report/departure/departure-report.thunks";
import {setAllDepartureReportsAction} from "../../../core/store/report/departure/departure-report.slices";
import Moment from "react-moment";
import {useRouter} from "next/router";
import {ReportListPageWrapper} from "../../../components/Layout";
import {eTable, IReportGetParams} from "../../../core/models";

const DepartureReportListPage = () => {
	const dispatch = useAppDispatch();
	const departureReport = useAppSelector(({departureReport}) => departureReport);

	const router = useRouter();

	const [filters, setFilters] = useState<IReportGetParams>({skip: 0, take: 20});
	useEffect(() => {
		const promises = [dispatch(getAllDepartureReportsThunk(filters))];

		return () => {
			promises.forEach((p) => p.abort());
			dispatch(setAllDepartureReportsAction({list: [], count: 0}));
		};
	}, [filters]);

	const onOpenReport = (reportId: number) => () => {
		void router.push(`/reports/departure/${reportId}`);
	};

	const onPagination = (pagination: {take: number; skip: number}) => {
		setFilters((prev) => ({...prev, ...pagination}));
	};

	const renderTableBodyRow = () => {
		return departureReport.list.map((report) => (
			<tr onClick={onOpenReport(report.id)} key={report.id}>
				<td>{report.id}</td>
				<td>{report.id}</td>
				<td>
					<Moment format="DD.MM.YYYY">{report.createdAt}</Moment>
				</td>
				<td>{report.organization.title.ru}</td>
				<td>{report.note ?? "-"}</td>
				<td>
					<AppBadge statusId={report.status.id} className="mx-auto">
						{report.status.title.ru}
					</AppBadge>
				</td>
			</tr>
		));
	};

	return (
		<>
			<Head>
				<title>Проделанная работа в регионах</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<h1 className="h1 text-center">Проделанная работа в регионах</h1>

			<AppDivider className="my-1.25" />

			<ReportListPageWrapper table={eTable.DepartureReport} cb={onPagination}>
				{departureReport.list.length > 0 ? (
					<AppTable linked wrapperClassName="p-0">
						<AppTable.THead>
							<tr>
								<th>ID</th>
								<th>Номер</th>
								<th>Дата</th>
								<th>Организация</th>
								<th>Комментарии</th>
								<th>Статус</th>
							</tr>
						</AppTable.THead>
						<AppTable.TBody>{renderTableBodyRow()}</AppTable.TBody>
					</AppTable>
				) : (
					"Список отчётов пуст."
				)}

				<div className="mt-auto">
					<AppDivider className="my-1.25" />
					<AppPagination take={filters.take} skip={filters.skip} totalCount={departureReport.count} cb={onPagination} />
				</div>
			</ReportListPageWrapper>
		</>
	);
};

export default DepartureReportListPage;
