import React, {useEffect, useState} from "react";
import Head from "next/head";
import {AppDivider, AppPagination, AppSetOfReportsFilter, AppTable, eCustomFilter} from "../../../components/Main";
import {useAppDispatch} from "../../../core/hooks";
import {getSetOfReportsThunks} from "../../../core/store/setOfReports/setOfReports.thunks";
import {ISetOfReportsScientificWorks, ISetOfReportsParams} from "../../../core/models";
import moment from "moment/moment";
import Moment from "react-moment";

const ScientificWorksSetOfReportsPage = () => {
	const dispatch = useAppDispatch();

	const [results, setResults] = useState<{count: number; data: ISetOfReportsScientificWorks[]}>();
	const [filters, setFilters] = useState<ISetOfReportsParams>({
		take: 20,
		skip: 0,
		start: moment().subtract(1, "months").startOf("month").format("yyyy-MM-DD"),
		end: moment().endOf("month").format("yyyy-MM-DD"),
		organizations: [],
	});

	useEffect(() => {
		const promise = dispatch(
			getSetOfReportsThunks({
				url: "scientificWorks",
				params: filters,
			}),
		);

		promise.then((action) =>
			setResults((prev) => {
				const result = action.payload as typeof results;
				if (result) {
					return {count: result.count, data: result.data};
				}
				return prev;
			}),
		);

		return () => {
			promise.abort();
		};
	}, [filters]);

	const onFilterSubmit = (params: ISetOfReportsParams) => {
		setFilters((prev) => ({...prev, ...params}));
	};

	const onPagination = (pagination: {take: number; skip: number}) => {
		setFilters((prev) => ({...prev, ...pagination}));
	};

	const renderRow = () => {
		return results?.data.map((r, i) => (
			<tr key={`${r.createdAt.toString()}-${i}`}>
				<td>
					<Moment format="DD.MM.YYYY">{r.createdAt}</Moment>
				</td>
				<td>{r._sum.localArticles}</td>
				<td>{r._sum.foreignArticles}</td>
				<td>{r._sum.cisArticles}</td>
				<td>{r._sum.scopusArticles}</td>
				<td>{r._sum.wosArticles}</td>
				<td>{r._sum.otherArticles}</td>
				<td>{r._sum.localLectures}</td>
				<td>{r._sum.foreignLectures}</td>
				<td>{r._sum.cisLectures}</td>
				<td>{r._sum.monographs}</td>
				<td>{r._sum.patents}</td>
				<td>{r._sum.benefits}</td>
				<td>{r._sum.recommendations}</td>
			</tr>
		));
	};

	return (
		<div className="pe-0 flex-col h-100">
			<Head>
				<title>Научные статьи, патенты и др.</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<h1 className="h1 text-center">Научные статьи, патенты и др.</h1>

			<AppDivider className="my-1.25" />

			<div className="pe-2.5">
				<AppSetOfReportsFilter
					disabledFilters={[
						eCustomFilter.countryId,
						eCustomFilter.places,
						eCustomFilter.specialityId,
						eCustomFilter.types,
					]}
					exportUrl="scientificWorks"
					onFilterSubmit={onFilterSubmit}
				/>
			</div>

			{(results?.data?.length || -1) > 0 ? (
				<AppTable wrapperClassName="mb-1.5">
					<AppTable.THead extended>
						<tr>
							<th rowSpan={2}>Дата</th>
							<th colSpan={6}>Количество статей</th>
							<th colSpan={3}>Количество лекций</th>
							<th colSpan={4}>Другие</th>
						</tr>
						<tr>
							<th>Местные</th>
							<th>Зарубежные</th>
							<th>СНГ</th>
							<th>Scopus</th>
							<th>WoS</th>
							<th>Другие</th>
							<th>Местные</th>
							<th>Зарубежные</th>
							<th>СНГ</th>
							<th>Монографии</th>
							<th>Патенты</th>
							<th>Методические пособия</th>
							<th>Методические рекомендации</th>
						</tr>
					</AppTable.THead>
					<AppTable.TBody>{renderRow()}</AppTable.TBody>
				</AppTable>
			) : (
				"Список отчётов пуст."
			)}
			<div className="mt-auto pe-2.5">
				<AppDivider className="my-1.25" />
				<AppPagination totalCount={results?.count} cb={onPagination} />
			</div>
		</div>
	);
};

export default ScientificWorksSetOfReportsPage;
