import React, {useEffect, useState} from "react";
import Head from "next/head";
import {AppDivider, AppPagination, AppSetOfReportsFilter, AppTable} from "../../../components/Main";
import {useAppDispatch} from "../../../core/hooks";
import {getSetOfReportsThunks} from "../../../core/store/setOfReports/setOfReports.thunks";
import {ISetOfReportsDaily, ISetOfReportsParams} from "../../../core/models";
import moment from "moment/moment";
import Moment from "react-moment";

const DailySetOfReportsPage = () => {
	const dispatch = useAppDispatch();

	const [results, setResults] = useState<{count: number; data: ISetOfReportsDaily[]}>();
	const [filters, setFilters] = useState<ISetOfReportsParams>({
		take: 20,
		skip: 0,
		start: moment().subtract(1, "months").startOf("month").format("yyyy-MM-DD"),
		end: moment().endOf("month").format("yyyy-MM-DD"),
		organizations: [],
	});

	useEffect(() => {
		const promise = dispatch(
			getSetOfReportsThunks({
				url: "daily",
				params: filters,
			}),
		);

		promise.then((action) =>
			setResults((prev) => {
				const result = action.payload as typeof results;
				if (result) {
					return {count: result.count, data: result.data};
				}
				return prev;
			}),
		);

		return () => {
			promise.abort();
		};
	}, [filters]);

	const onFilterSubmit = (params: ISetOfReportsParams) => {
		setFilters((prev) => ({...prev, ...params}));
	};

	const onPagination = (pagination: {take: number; skip: number}) => {
		setFilters((prev) => ({...prev, ...pagination}));
	};

	const renderRow = () => {
		return results?.data.map((r, i) => (
			<tr key={`${r.createdAt.toString()}-${i}`}>
				<td>
					<Moment format="DD.MM.YYYY">{r.createdAt}</Moment>
				</td>
				<td>{r._sum.totalBeds}</td>
				<td>{r._sum.occupiedBeds}</td>
				<td>{r._sum.freeBeds}</td>
				<td>{r._sum.outPatientsRes}</td>
				<td>{r._sum.inPatientsRes}</td>
				<td>{r._sum.otherPatientsRes}</td>
				<td>{r._sum.outPatients}</td>
				<td>{r._sum.inPatients}</td>
				<td>{r._sum.polyclinicCash}</td>
				<td>{r._sum.polyclinicReceiptsCash}</td>
				<td>{r._sum.hospitalCash}</td>
				<td>{r._sum.hospitalReceiptsCash}</td>
				<td>{r._sum.gfms}</td>
				<td>{r._sum.otherReceipts}</td>
			</tr>
		));
	};

	return (
		<div className="pe-0 flex-col h-100">
			<Head>
				<title>Ежедневный отчёт</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<h1 className="h1 text-center">Ежедневный отчёт</h1>

			<AppDivider className="my-1.25" />

			<div className="pe-2.5">
				<AppSetOfReportsFilter exportUrl="daily" onFilterSubmit={onFilterSubmit} />
			</div>
			{(results?.data?.length || -1) > 0 ? (
				<AppTable wrapperClassName="mb-1.5">
					<AppTable.THead extended>
						<tr>
							<th rowSpan={3}>Дата</th>
							<th colSpan={3}>Количество коек</th>
							<th colSpan={3}>Количество пациентов (резиденты)</th>
							<th colSpan={2}>Количество пациентов (не резиденты)</th>
							<th colSpan={6}>Поступление денег</th>
						</tr>
						<tr>
							<th rowSpan={2}>Итого</th>
							<th rowSpan={2}>Занято</th>
							<th rowSpan={2}>Свободно</th>
							<th rowSpan={2}>Амбулаторно</th>
							<th rowSpan={2}>Стационар</th>
							<th rowSpan={2}>В том числе с направлением</th>
							<th rowSpan={2}>Амбулаторно</th>
							<th rowSpan={2}>Стационар</th>
							<th colSpan={2}>Поликлиника</th>
							<th colSpan={2}>Стационар</th>
							<th rowSpan={2}>ГФМС</th>
							<th rowSpan={2}>Другие поступления</th>
						</tr>
						<tr>
							<th>Касса</th>
							<th>Перечисления</th>
							<th>Касса</th>
							<th>Перечисления</th>
						</tr>
					</AppTable.THead>
					<AppTable.TBody>{renderRow()}</AppTable.TBody>
				</AppTable>
			) : (
				"Список отчётов пуст."
			)}
			<div className="mt-auto pe-2.5">
				<AppDivider className="my-1.25" />
				<AppPagination totalCount={results?.count} cb={onPagination} />
			</div>
		</div>
	);
};

export default DailySetOfReportsPage;
